version: "3.8"
services:
  authentication-service:
    container_name: authConatainer
    build: ./backend/authentication-service/
    ports:
      - "2222:2222" 
    volumes:
      - ./backend/authentication-service:/app
    environment:
      - API_KEY=apikey
      - DB=mongodb+srv://admin:admin@lms.mqm8lgp.mongodb.net/authentication-service?retryWrites=true&w=majority&appName=LMS
      - JWTPRIVATEKEY=shit01
      - SALT=10

  api-gateway:
    container_name: apiContainer
    build: ./backend/api-gateway/
    ports:
      - "5000:5000"
    volumes:
      - ./backend/api-gateway:/app
    environment:
      - SERVICE_NAME_AUTH=http://authentication-service:2222
      - SERVICE_NAME_LEC=http://lecturer-service:1113

  lecturer-service:
    container_name: lecContainer
    build: ./backend/lecturer-service/
    ports:
      - "1113:1113"
    volumes:
      - ./backend/authentication-service:/app
  payment-service:
    container_name: app3
    build: ./backend/payment-service-py/
    ports:
      - "3001:3001"
    volumes:
      - ./backend/payment-service-py:/app
    environment:
      STRIPE_SECRET_KEY: "sk_test_51PBff92LxlKPHBMAiyaAfpPv4m43et8Lo3JSoce8Vy6hODBwhwcOghK5UnPWsKEqHN1B0KYScn4raFtoFaYQh5tW00MSqrccuW"
      CLIENT_URL: "http://localhost:5173"
