version: "3.8"
services:
  api-gateway:
    container_name: app1
    build: ./backend/api-gateway/
    ports:
      - "5000:5000"
    volumes:
      - ./backend/api-gateway:/app
    environment:
      - SERVICE_NAME_AUTH=http://authentication-service
  authentication-service:
    container_name: app2
    build: ./backend/authentication-service/
    ports:
      - "1112:1112"
    volumes:
      - ./backend/authentication-service:/app
    environment:
      - PORT=1112
      - MONGOSTRING=mongodb+srv://admin:admin@lms.mqm8lgp.mongodb.net/authentication-service?retryWrites=true&w=majority&appName=LMS
      - JWTPRIVATEKEY=shit01
      - SALT=10
