apiVersion: v1
kind: Namespace
metadata:
  name: lms

---

apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  namespace: lms
spec:
  ports:
    - protocol: TCP
      port: 2222
      targetPort: 2222
  selector:
    app: authentication
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-deployment
  namespace: lms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: authentication
          image: authentication-service:latest
          ports:
            - containerPort: 2222
          env:
            - name: API_KEY
              value: apikey
            - name: DB
              value: "mongodb+srv://admin:admin@lms.mqm8lgp.mongodb.net/authentication-service?retryWrites=true&w=majority&appName=LMS"
            - name: JWTPRIVATEKEY
              value: shit01
            - name: SALT
              value: "10"

---

apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: lms
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: gateway
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  namespace: lms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: api-gateway:latest
          ports:
            - containerPort: 5000
          env:
            - name: SERVICE_NAME_LEC
              value: "http://lecturer-service:1113"
            - name: SERVICE_NAME_AUTH
              value: "http://authentication-service:2222"
            - name: SERVICE_NAME_PAY
              value: "http://payment-service:3001"
            - name: SERVICE_NAME_COURSE
              value: "http://coursemanagement-service:3002"
            - name: SERVICE_NAME_NOTIFICATION
              value: "http://notification-service:1114"
            - name: SERVICE_NAME_PROFILE
              value: "http://profile-management-service:1117"
            - name: SERVICE_NAME_STORAGE
              value: "http://storage-service:1234"

---

apiVersion: v1
kind: Service
metadata:
  name: lecturer-service
  namespace: lms
spec:
  ports:
    - protocol: TCP
      port: 1113
      targetPort: 1113
  selector:
    app: lecturers
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: lecturer-deployment
  namespace: lms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lecturers
  template:
    metadata:
      labels:
        app: lecturers
    spec:
      containers:
        - name: lecturers
          image: lecturer-service:latest
          ports:
            - containerPort: 1113

---

apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: lms
spec:
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  selector:
    app: payments
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  namespace: lms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: payment-service-py:latest
          ports:
            - containerPort: 3001
          env:
            - name: STRIPE_SECRET_KEY
              value: "sk_test_51PBff92LxlKPHBMAiyaAfpPv4m43et8Lo3JSoce8Vy6hODBwhwcOghK5UnPWsKEqHN1B0KYScn4raFtoFaYQh5tW00MSqrccuW"
            - name: CLIENT_URL
              value: "http://localhost:5173"

---

apiVersion: v1
kind: Service
metadata:
  name: coursemanagement-service
  namespace: lms
spec:
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  selector:
    app: courses
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: coursemanagement-deployment
  namespace: lms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: courses
  template:
    metadata:
      labels:
        app: courses
    spec:
      containers:
        - name: courses
          image: coursemanagement-service:latest
          ports:
            - containerPort: 3002
          env:
            - name: DB
              value: "mongodb+srv://admin:admin@lms.mqm8lgp.mongodb.net/coursemanagement-service?retryWrites=true&w=majority&appName=LMS"

---

apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: lms
spec:
  ports:
    - protocol: TCP
      port: 1114
      targetPort: 1114
  selector:
    app: notifications
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  namespace: lms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - name: notifications
          image: notification-service:latest
          ports:
            - containerPort: 1114
          env:
            - name: PORT
              value: "1114"
            - name: MONGODB_URI
              value: "mongodb+srv://admin:admin@lms.mqm8lgp.mongodb.net/notification-service?retryWrites=true&w=majority&appName=LMS"

---

apiVersion: v1
kind: Service
metadata:
  name: storage-service
  namespace: lms
spec:
  ports:
    - protocol: TCP
      port: 1234
      targetPort: 1234
  selector:
    app: storage
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-deployment
  namespace: lms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
        - name: storage
          image: storage-service:latest
          ports:
            - containerPort: 1234
